# Generated by Django 3.2.5 on 2022-09-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprecom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spre_url',
            name='number_of_recs',
            field=models.IntegerField(default=1),
        ),
    ]
