# Generated by Django 3.2.5 on 2022-09-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprecom_app', '0002_spre_url_number_of_recs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='spre_URL',
            new_name='React',
        ),
    ]
